// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDicYRRCv0xHVQ0XjHwbMMKZugOHmmfSLY',
    appId: '1:554637904465:web:a14640b4850d4f90198670',
    messagingSenderId: '554637904465',
    projectId: 'fir-chatapp-55e7f',
    authDomain: 'fir-chatapp-55e7f.firebaseapp.com',
    storageBucket: 'fir-chatapp-55e7f.appspot.com',
    measurementId: 'G-9PQEV5WKD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNHqzHOrfqhSv9Ppp1eXUW7iSljVn8Cj0',
    appId: '1:554637904465:android:280724b5c783726c198670',
    messagingSenderId: '554637904465',
    projectId: 'fir-chatapp-55e7f',
    storageBucket: 'fir-chatapp-55e7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeAHG_rt3SOsH2QHi1cG-RjJYGDjQx7xc',
    appId: '1:554637904465:ios:d2b93605f303e61c198670',
    messagingSenderId: '554637904465',
    projectId: 'fir-chatapp-55e7f',
    storageBucket: 'fir-chatapp-55e7f.appspot.com',
    iosClientId: '554637904465-545tqeaihpf10ppijj8ivf2101jerml7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeAHG_rt3SOsH2QHi1cG-RjJYGDjQx7xc',
    appId: '1:554637904465:ios:d2b93605f303e61c198670',
    messagingSenderId: '554637904465',
    projectId: 'fir-chatapp-55e7f',
    storageBucket: 'fir-chatapp-55e7f.appspot.com',
    iosClientId: '554637904465-545tqeaihpf10ppijj8ivf2101jerml7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDicYRRCv0xHVQ0XjHwbMMKZugOHmmfSLY',
    appId: '1:554637904465:web:9d387af25b139319198670',
    messagingSenderId: '554637904465',
    projectId: 'fir-chatapp-55e7f',
    authDomain: 'fir-chatapp-55e7f.firebaseapp.com',
    storageBucket: 'fir-chatapp-55e7f.appspot.com',
    measurementId: 'G-QSR6ENT731',
  );

}